stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt update -qy
  - apt install python3 python3-pip virtualenvwrapper -qy
  - virtualenv --python=python3 v_env/
  - source v_env/bin/activate
  - pip install -r requirements.txt
  - python3 manage.py test 

staging:
  stage: deploy
  script:
    - echo "deployed"
  only:
    - master
