# Generated by Django 3.1.6 on 2021-02-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180312_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Giornalista',
            new_name='Regista',
        ),
        migrations.AlterModelOptions(
            name='regista',
            options={'verbose_name': 'Regista', 'verbose_name_plural': 'Registi'},
        ),
        migrations.RenameField(
            model_name='articolo',
            old_name='giornalista',
            new_name='regista',
        ),
    ]
