# Generated by Django 3.1.6 on 2021-02-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210215_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('contenuto', models.TextField()),
                ('regista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='news.regista')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Film',
            },
        ),
        migrations.DeleteModel(
            name='Articolo',
        ),
    ]
