# Generated by Django 3.1.6 on 2021-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210215_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='anno',
            field=models.TextField(default=1985),
            preserve_default=False,
        ),
    ]
